"use client";
import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Settings, FileJson, Code, Send } from 'lucide-react';
import { guideCode } from '../lib/api';

export default function SetupPanel({ onComplete }: { onComplete: (specs: any) => void }) {
    const [globalJson, setGlobalJson] = useState("");
    const [showCodeHelper, setShowCodeHelper] = useState(false);
    const [userCode, setUserCode] = useState("");
    const [chatMessages, setChatMessages] = useState<{ type: 'user' | 'ai', content: string }[]>([]);
    const [loading, setLoading] = useState(false);
    const [sessionId] = useState(`sess_setup_${Math.random().toString(36).substr(2, 9)}`);
    const chatEndRef = useRef<HTMLDivElement>(null);

    const handleInitialize = () => {
        try {
            const parsed = JSON.parse(globalJson);
            // Validate minimal fields
            if (!parsed.model_version || !parsed.global_importance) {
                alert("Invalid Global JSON. Must contain 'model_version' and 'global_importance'.");
                return;
            }

            onComplete({
                model_version: parsed.model_version,
                schema_spec: {}, // Not needed as it's implicit in JSON now
                global_json: parsed
            });
        } catch (e) {
            alert("Invalid JSON format.");
        }
    };

    const handleGetGuide = async () => {
        if (!userCode.trim()) return;
        setLoading(true);
        const code = userCode;
        setUserCode("");
        setChatMessages(prev => [...prev, { type: 'user', content: "Analyze my code and help me generate Global JSON: " + code.substring(0, 50) + "..." }]);

        try {
            const res = await guideCode(sessionId, "Here is my model code, please help me write the 'explain_global' function to generate the Global JSON structure you need:\n\n" + code);
            setChatMessages(prev => [...prev, { type: 'ai', content: res.response }]);
        } catch (e) {
            setChatMessages(prev => [...prev, { type: 'ai', content: "Failed to analyze code." }]);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [chatMessages]);

    return (
        <div className="bg-slate-900/50 backdrop-blur-md border border-slate-700 rounded-xl p-6 shadow-2xl relative overflow-hidden">
            {/* Feature Toggle: Code Helper */}
            <div className="absolute top-6 right-6 z-10">
                <button
                    onClick={() => setShowCodeHelper(!showCodeHelper)}
                    className="flex items-center gap-2 text-xs font-mono text-purple-400 hover:text-purple-300 transition-colors"
                >
                    <Code className="w-4 h-4" /> {showCodeHelper ? "Hid Code Helper" : "Need help generating JSON?"}
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 transition-all">
                {/* Left: Input */}
                <div className={showCodeHelper ? '' : 'md:col-span-2'}>
                    <h2 className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-cyan-300 bg-clip-text text-transparent mb-6 flex items-center gap-2">
                        <Settings className="w-6 h-6 text-blue-400" /> System Configuration
                    </h2>

                    <div className="p-4 bg-blue-500/10 rounded-lg border border-blue-500/20 text-sm text-blue-200 mb-6">
                        Paste the <strong>Global JSON</strong> generated by your model explainer code.
                    </div>

                    <div className="min-h-[300px]">
                        <label className="block text-sm text-slate-400 mb-1 flex items-center gap-2">
                            <FileJson className="w-4 h-4" /> Global Explanation JSON
                        </label>
                        <textarea
                            value={globalJson}
                            onChange={e => setGlobalJson(e.target.value)}
                            placeholder='{ "model_version": "v1", "global_importance": [...] }'
                            className="w-full h-[300px] bg-slate-950/50 border border-slate-700 rounded-lg p-3 text-emerald-300 font-mono text-sm focus:ring-2 focus:ring-emerald-500 outline-none resize-none custom-scrollbar"
                        />
                    </div>

                    <div className="mt-6 flex justify-end">
                        <button
                            onClick={handleInitialize}
                            className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white px-8 py-3 rounded-lg font-medium shadow-lg shadow-blue-500/20 transition-all hover:scale-[1.02]"
                        >
                            Visualize Global Explanation
                        </button>
                    </div>
                </div>

                {/* Right: Code Helper Overlay/Side */}
                <AnimatePresence>
                    {showCodeHelper && (
                        <motion.div
                            initial={{ opacity: 0, x: 20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: 20 }}
                            className="bg-slate-950 border border-slate-800 rounded-xl p-4 flex flex-col h-[500px]"
                        >
                            <h3 className="text-purple-400 font-bold mb-2 text-sm flex items-center gap-2">
                                <BotIcon /> Code Assistant
                            </h3>
                            <p className="text-slate-500 text-xs mb-4">
                                Paste your model training code below. I will write the Python code to generate the Global JSON for you.
                            </p>

                            <div className="flex-1 overflow-y-auto mb-4 bg-slate-900/50 rounded p-2 custom-scrollbar">
                                {chatMessages.length === 0 && (
                                    <div className="text-center text-slate-600 text-xs mt-10">
                                        No messages yet. Paste code to start.
                                    </div>
                                )}
                                {chatMessages.map((m, i) => (
                                    <div key={i} className={`mb-3 ${m.type === 'user' ? 'text-right' : 'text-left'}`}>
                                        <div className={`inline-block p-2 rounded-lg text-xs max-w-[90%] ${m.type === 'user' ? 'bg-purple-900/50 text-purple-100' : 'bg-slate-800 text-slate-300'}`}>
                                            {m.type === 'ai' ? (
                                                <div className="whitespace-pre-wrap font-mono">{m.content}</div>
                                            ) : m.content}
                                        </div>
                                    </div>
                                ))}
                                {loading && <div className="text-slate-500 text-xs animate-pulse">Analyzing code...</div>}
                                <div ref={chatEndRef} />
                            </div>

                            <div className="flex gap-2">
                                <textarea
                                    value={userCode}
                                    onChange={e => setUserCode(e.target.value)}
                                    placeholder="Paste python code here..."
                                    className="flex-1 bg-slate-900 border border-slate-700 rounded p-2 text-xs font-mono text-slate-300 resize-none header-none focus:border-purple-500 h-20"
                                />
                                <button
                                    onClick={handleGetGuide}
                                    disabled={loading || !userCode.trim()}
                                    className="bg-purple-600 hover:bg-purple-500 disabled:opacity-50 text-white rounded px-4 flex items-center justify-center"
                                >
                                    <Send className="w-4 h-4" />
                                </button>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}

function BotIcon() {
    return (
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2a2 2 0 0 1 2 2v2a2 2 0 0 1-2 2 2 2 0 0 1-2-2V4a2 2 0 0 1 2-2z" /><path d="m8 22-1-4h10l-1 4" /><circle cx="12" cy="12" r="9" /></svg>
    )
}
